#!/bin/sh
#
# Create lxc-br for subutai
#

[ -d /var/spool/subutai ] || mkdir /var/spool/subutai

ovs-vsctl show | grep ${SUBUTAI_SWITCH} >/dev/null || (

	ovs-vsctl add-br ${SUBUTAI_SWITCH}
	ip link set ${SUBUTAI_SWITCH} up

)

ip addr show | grep ${SUBUTAI_IP} >/dev/null || (

	ip addr add ${SUBUTAI_IP}/24 dev ${SUBUTAI_SWITCH}

)

dnsmasq -k -p 0 --interface=${SUBUTAI_SWITCH} --dhcp-range=${SUBUTAI_DHCP_RANGE} --dhcp-leasefile=/var/spool/subutai/dnsmasq.leases --dhcp-option=6,${SUBUTAI_IP} &

exit 0

# vim: ts=4 et nowrap autoindent