#!/bin/sh
#
# Create lxc-br for subutai
#

LOG="logger -t subutai-ovs -p local0.debug "

$LOG "subutai-ovs starting"

[ -d /var/spool/subutai ] || mkdir /var/spool/subutai

$LOG "checking if ${SUBUTAI_SWITCH} exists"
ovs-vsctl show | grep ${SUBUTAI_SWITCH} >/dev/null || (

	$LOG "did not - creating ${SUBUTAI_SWITCH}"

	ovs-vsctl add-br ${SUBUTAI_SWITCH}

)

$LOG "checking if ${SUBUTAI_SWITCH} is up"
ip link list | grep ${SUBUTAI_SWITCH} | grep "UP" >/dev/null || (

	$LOG "it was not - setting ${SUBUTAI_SWITCH} to up"
	ip link set ${SUBUTAI_SWITCH} up

)

ip addr show | grep ${SUBUTAI_IP} >/dev/null || (

	ip addr add ${SUBUTAI_IP}/24 dev ${SUBUTAI_SWITCH}

)

$LOG "Ensure IP forwarding is enabled"
echo 1 >/proc/sys/net/ipv4/ip_forward

$LOG "Masquerading outgoing traffic"
iptables -t nat -A POSTROUTING -j MASQUERADE

exit 0

# vim: ts=4 et nowrap autoindent
