#!/bin/sh
#
# Create lxc-br for subutai
#

LOG="logger -t subutai-ovs -p local0.debug "

$LOG "starting"

[ -d /var/spool/subutai ] || mkdir /var/spool/subutai

$LOG "checking if ${SUBUTAI_SWITCH} exists"
ovs-vsctl show | grep ${SUBUTAI_SWITCH} >/dev/null || (

	$LOG "did not - creating ${SUBUTAI_SWITCH}"

	ovs-vsctl add-br ${SUBUTAI_SWITCH}

)

$LOG "checking if ${SUBUTAI_SWITCH} is up"
ip link list | grep ${SUBUTAI_SWITCH} | grep "UP" >/dev/null || (

	$LOG "it was not - setting ${SUBUTAI_SWITCH} to up"
	ip link set ${SUBUTAI_SWITCH} up

)

ip addr show | grep ${SUBUTAI_IP} >/dev/null || (

	ip addr add ${SUBUTAI_IP}/24 dev ${SUBUTAI_SWITCH}

)

$LOG "Ensure IP forwarding is enabled"
echo 1 >/proc/sys/net/ipv4/ip_forward

$LOG "Redirect DNS and DHCP traffic"
iptables -t nat -A PREROUTING -d ${SUBUTAI_IP} -p udp --dport 53 -j DNAT --to-destination ${SUBUTAI_IP}:${SUBUTAI_DNS_PORT}
#iptables -t nat -A PREROUTING -d ${SUBUTAI_IP} -p udp --sport bootps -j DNAT --to-destination ${SUBUTAI_IP}:${SUBUTAI_BOOTPS_PORT}
#iptables -t nat -A PREROUTING -d ${SUBUTAI_IP} -p udp --sport bootpc -j DNAT --to-destination ${SUBUTAI_IP}:${SUBUTAI_BOOTPC_PORT}

$LOG "Masquerading outgoing traffic"
iptables -t nat -A POSTROUTING -j MASQUERADE

#dnsmasq -q --port ${SUBUTAI_DNS_PORT} --dhcp-alternate-port=${SUBUTAI_BOOTPS_PORT},${SUBUTAI_BOOTPC_PORT} --interface=${SUBUTAI_SWITCH} --dhcp-range=${SUBUTAI_DHCP_RANGE} --dhcp-leasefile=/var/spool/subutai/dnsmasq.leases --dhcp-option=6,${SUBUTAI_IP} 

$LOG "Starting dnsmasq"


exit 0

# vim: ts=4 et nowrap autoindent
