#!/bin/bash

. /etc/default/subutai-ovs

LOG="logger -t subutai-create-interface -p local0.debug "

$LOG "Running for $1"

vlan="$(grep '#vlan_id' ${SUBUTAI_LXC}/$1/config | awk '{print $3}')"
gateway="$(grep 'lxc.network.ipv4.gateway' ${SUBUTAI_LXC}/$1/config | awk '{print $3}')"

$LOG "vlan = $vlan"

if [ "$vlan" ]; then
        ovs-vsctl --may-exist add-br gw-$vlan
	ovs-vsctl set bridge gw-$vlan stp-enable=true
	ovs-vsctl --if-exists set port gw-$vlan "tag=$vlan"
        ovs-vsctl --if-exists del-port gw-$vlan $5
        ovs-vsctl add-port gw-$vlan $5 tag=$vlan
        
	/bin/ip addr add $gateway/24 dev gw-$vlan
	/bin/ip link set gw-$vlan up

	ipaddr=$(grep "lxc.network.ipv4 " ${SUBUTAI_LXC}/$1/config | awk -F'[ /]' '{print $3}')
	port=$(expr 10000 + `echo $ipaddr | cut -d'.' -f4`)
	if [ "$ipaddr" != "" ]; then
		for i in {1..10}; do
			if [ "$(iptables-save | grep -c "A PREROUTING -i p2p$vlan -p tcp -m tcp --dport $port -j DNAT --to-destination $ipaddr:22")" != "0" ]; then
				break
			fi
			iptables -t nat -A PREROUTING -i p2p$vlan -p tcp -m tcp --dport $port -j DNAT --to-destination $ipaddr:22
		done
	fi
	#of_port=$(ovs-ofctl queue-get-config gw-$vlan gw-$vlan | cut -d"=" -f3)
        ovs-ofctl add-flow gw-$vlan "priority=2600,in_port=LOCAL,ip,nw_src=10.10.10.1 actions=normal"
        ovs-ofctl add-flow gw-$vlan "priority=2600,in_port=LOCAL,ip,nw_src=$gateway actions=normal"
        ovs-ofctl add-flow gw-$vlan "priority=2500,in_port=LOCAL,ip,nw_src=10.0.0.0/8 actions=drop"
        ovs-ofctl add-flow gw-$vlan "priority=2500,in_port=LOCAL,ip,nw_src=172.16.0.0/12 actions=drop"
        ovs-ofctl add-flow gw-$vlan "priority=2500,in_port=LOCAL,ip,nw_src=192.168.0.0/16 actions=drop"

else
        ovs-vsctl --if-exists del-port lxc-br $5
        ovs-vsctl --may-exist add-port lxc-br $5
fi

rate="$(grep 'subutai.network.ratelimit' ${SUBUTAI_LXC}/$1/config | awk '{print $3}')"
if [ "$rate" != "" ]; then
        ovs-vsctl set interface $5 "ingress_policing_rate="+$rate
        ovs-vsctl set interface $5 "ingress_policing_burst="+$((rate/10))
fi
